apiVersion: batch/v1
kind: Job
metadata:
  name: copy-db-job
spec:
  template:
    spec:
      containers:
      - name: copy-db
        image: macarious25siv/books:V6
        command: ['sh', '-c', 'cp -r /app/db/* /mnt/data/bookmanage/']
        volumeMounts:
        - name: bookmanage-storage
          mountPath: /mnt/data/bookmanage
      restartPolicy: OnFailure
      volumes:
      - name: bookmanage-storage
        persistentVolumeClaim:
          claimName: my-pv-claim2
